name: Run Cppcheck

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Cppcheck
        uses: tonybaloney/cppcheck-action@master
        with:
          path: 'unit_test'  # Update this with the relative path to the code you want to check
          level: 'warning'   # Optional: specify the cppcheck level (default is 'warning')
          opts: '--additional-flags'  # Optional: add additional command line flags and options here
